<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Sideways_to_TaxStream</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>e7f76795-6cf7-462a-8c79-a04b7cda1754</testSuiteGuid>
   <testCaseLink>
      <guid>0724974d-9f9b-45ed-84c4-0bc789d6bbea</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TaxStream_Automation/Manage Views/TCID_5096_Verify Manage View button on top right corner of TaxStream landing page</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2ceb5a1-77b7-4e6d-a09f-92392e75c996</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db7841f8-f254-4cc6-ba32-f0a091f5652c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6dc3809a-b800-49a2-a375-60bca020e11c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d27f12b1-87f9-4fce-ac59-245e09b2a10b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d9d79a4-de94-4ced-b200-99b41e130c91</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab9a3435-8f23-4172-ba4d-58df18201378</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>182a6b98-b4d3-4767-a6a7-f9a295be6206</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5497a90d-9890-453f-a11e-618d49c6144d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TaxStream_Automation/Manage Views/TCID_5097_Verify Manage View button on top right corner of TaxStream landing page is clickable for empty or existing loadmapid</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8ab0376-9db6-44f3-bce2-85c3e156b584</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0db8c64-d04d-43c6-ae11-acbf9ddfa8ba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b40c08dd-d2bb-4062-af96-2a90f3aa9862</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>986fe0af-1d58-44a1-8d1c-657af622aabe</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>451a6437-6fc0-4054-b688-1e0550642076</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TaxStream_Automation/Manage Views/TCID_5098_Click to Manage View button and verify loading custom Views list popup is displaying on loader config page</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>39c9af91-97d5-456a-a7b5-228565585769</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3946dd6b-a058-4e6e-8b9c-b12b6d43050d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ed35b79-86f5-451d-9ad9-9105acc349b9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>459ac238-fb24-4844-a1ac-aee08a4d67d3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TaxStream_Automation/Manage Views/TCID_5099_Verify the loader config View section w.r.t columns on grid table and Add View button</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76cfd1a9-23be-4548-ac25-aaac52745ca2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b6bcf99-3a22-4144-a7e3-ed87b14a9121</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1fb5f1d7-f15e-44a3-b446-4728ab04fe98</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>46fae3ae-1eb6-4fc1-a38f-98b6e7c46266</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TaxStream_Automation/Manage Views/TCID_5100_Verify on Views section, click to Add View button</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4aa8df63-3046-4c92-ad1e-f38863177935</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b5abbc0-93d7-417c-8713-d1497a6ca5de</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>49ff86e2-bbfc-4a51-94b8-6f1cd3dc99bc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6d400755-a8dd-4ca9-9032-34d021c62ebe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TaxStream_Automation/Manage Views/TCID_5102_Verify by adding an New Custom View on loader config page</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2da381c0-629b-43cb-9c96-9a173bd18165</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a975198-b4b0-4a39-993f-42ea304ab3d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1ed5c49-7b42-47a2-8d83-7a137390d994</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9b1dd299-16f2-4a68-abd3-0ccf3d37c6ec</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TaxStream_Automation/Manage Views/TCID_5103_Verify Action buttons (Edit and Delete) after adding the New Custom View list for loader config</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cbedbdf2-f048-4687-a9f2-2d26f490a16d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>667d8157-927b-493a-afa8-0f4f736403f0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e0f2e5e-953f-499e-b86a-c85ebb19bf79</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>eeebf87f-e409-4215-98f2-9a6abd62e169</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TaxStream_Automation/Manage Views/TCID_5104_Verify by editing the existing Custom View List and click to Update the data should be updated</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66557a8b-4459-4e16-9220-38d2587080ff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1445c398-8729-45dd-9d77-f7810eaa9184</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b5ff796-fc0d-456d-bd90-89161b21dab8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ff6a0dd0-cc52-4e1d-abd5-7a314d28d127</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TaxStream_Automation/Manage Views/TCID_5110_Verify Custom View Lists accepts the duplicates names for Views</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>261117bf-7be5-4539-a9e8-a16abee9a0af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71c93dc1-83d0-4f54-a0d8-aa17e22c36f7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f938e4c9-5524-46f4-b7b3-c1cfc3115c8b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5e32c8bc-3500-4880-ab90-6b42f03ee1ba</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TaxStream_Automation/Manage Views/TCID_5111_Verify all the created Views should be displayed in Source Tables List</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a4ff413-9d5e-48a0-b85e-6c3ec6a2aec5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>634d8cd6-a34b-40b7-8562-d39a389a0de8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>675783fc-441c-4e44-b57a-3b2bd3f6eff8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3bb82124-1a57-43f3-8fb1-6c5278c811eb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d25cbc3-69e2-476f-90fa-a38a0a940652</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
