<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AutoVerification_Multiple_CustomCheck_Pencil_Icon</name>
   <tag></tag>
   <elementGuidId>0de68d31-2c06-442d-885a-2d76b53f3882</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;valObj&quot;]//table/tbody/tr[4]/td[5]/a/i</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
