<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>CreateNewSource</description>
   <name>btn_Save_CreateNewSource</name>
   <tag></tag>
   <elementGuidId>d4129b9b-ce9e-40a2-860e-e768c9ba9bec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;save&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
