<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>parcel_Col_Ptxnumber</name>
   <tag></tag>
   <elementGuidId>ed2b4eb7-c8a7-406d-9bcc-62bd21988c62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;parcelTable_wrapper&quot;]//div[1]/table/thead[1]/tr/th[6]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
