<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ALT_LoadMap_Stg_Table_Column_Lookup</name>
   <tag></tag>
   <elementGuidId>2c543c3d-312a-4081-8883-c8028015e921</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;assr_lookup_type&quot;]/div[4]/div[1]/span/h5</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
