<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>LoadMap</description>
   <name>LM_Label_LoadMap</name>
   <tag></tag>
   <elementGuidId>d88e548d-dd98-4ff9-ad16-07436e87ca78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class=&quot;form-row&quot;]/div[2]/label[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
