<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>plus_btn_NewSourceTemplateTable</name>
   <tag></tag>
   <elementGuidId>46004d01-8e72-4665-a600-fb1c8b96913d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;page-top&quot;]/div/div[1]/div[3]/div[2]/div/div[2]//div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
