<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Delete_NO</name>
   <tag></tag>
   <elementGuidId>9912b677-adc0-4d89-ae51-1a428c379734</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ace-button[@aria-label='No']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
