<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SourceGrid_btn_Save</name>
   <tag></tag>
   <elementGuidId>9b8d8880-8c37-4697-bb20-b4c4b2d5e697</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ace-button[@aria-label='Save']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
