<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SourceGrid_Output</name>
   <tag></tag>
   <elementGuidId>2cb5c928-98c6-4ba9-890e-fc0a697b0c0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ace-link[@aria-label='Output']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
