<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SourceGrid_label_Alias</name>
   <tag></tag>
   <elementGuidId>c5e7817f-3ffd-40a7-8898-128ee245a606</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ace-form-field[2]//label</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
