<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RegexTester_btn_Submit</name>
   <tag></tag>
   <elementGuidId>362bcdd8-5d25-4c0e-aa11-d0e427398908</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;regexTesterVue&quot;]/div[2]/div/form/div[1]/div[2]/span/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
