<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>stg_ga_Test_1_Columnheading</name>
   <tag></tag>
   <elementGuidId>7d21046e-4d12-449f-a4ae-cc26a466d121</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;tableColumnVue&quot;]/div[2]/div[1]/div/table/thead/tr/th[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
