<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>PtxTech_Logo</description>
   <name>PtxTech_Logo</name>
   <tag></tag>
   <elementGuidId>c57534ea-48f5-4686-a0af-679a3c4d97ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;mainNav&quot;]/a/img</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
