<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>ResetPage_ForgotPwd_Heading</description>
   <name>ResetPage_ForgotPwd_Heading</name>
   <tag></tag>
   <elementGuidId>6fd00103-5086-4136-9c0d-097fb0d7f2f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class=&quot;container&quot;]/div[1]/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
