<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>ResetPage_Emailaddress</description>
   <name>ResetPage_Emailaddress</name>
   <tag></tag>
   <elementGuidId>62bde2c4-08ef-4621-89fe-b36963bcf599</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class=&quot;col-md-12&quot;]/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
