<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>//*[@class=&quot;nav-item&quot;][1]</description>
   <name>LoaderConfiglist_Tab</name>
   <tag></tag>
   <elementGuidId>e2cdc454-0a61-497b-9b37-97c3a22bb7ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class=&quot;nav-item&quot;][2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
