<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Organization_SignIn_Page</name>
   <tag></tag>
   <elementGuidId>5d5d79b2-6c08-4c57-8f62-3fe5cef8620c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
